// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use diesel_codegen::Queryable;

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i64,
    pub uuid: String,
    pub name: String,
    pub email: String,
    pub enc_key: String,
    pub customer_id: String,
}
